/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.senac.drogarara.gui;

import com.senac.drogarara.conexao.Conexao;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import com.senac.drogarara.model.Produto;
import com.senac.drogarara.DAO.ProdutoDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class ProdutoFormView extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoFormView
     */
    public ProdutoFormView() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tListaProdutos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtConsNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtConsCod = new javax.swing.JTextField();
        btnAddProd = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnConsNm = new javax.swing.JButton();
        btnConsCod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        tListaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "QTD Estoque", "Categoria", "Valor", "Descrição"
            }
        ));
        jScrollPane1.setViewportView(tListaProdutos);

        jLabel1.setText("Consulta por nome: ");

        jLabel2.setText("Codigo do produto:");

        btnAddProd.setIcon(new javax.swing.ImageIcon("/home/david/Documentos/projetoDP/Drogarara/src/com/senac/drogarara/img/addButtonSmall.png")); // NOI18N
        btnAddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon("/home/david/Documentos/projetoDP/Drogarara/src/com/senac/drogarara/img/btnDeleteSmall.png")); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAtualizar.setIcon(new javax.swing.ImageIcon("/home/david/Documentos/projetoDP/Drogarara/src/com/senac/drogarara/img/updateBtnSmall.png")); // NOI18N
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("Lista de Produtos");

        btnVoltar.setIcon(new javax.swing.ImageIcon("/home/david/Documentos/projetoDP/Drogarara/src/com/senac/drogarara/img/btnReturnSmall.png")); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnConsNm.setIcon(new javax.swing.ImageIcon("/home/david/Vídeos/searchBtnSmall.png")); // NOI18N
        btnConsNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsNmActionPerformed(evt);
            }
        });

        btnConsCod.setIcon(new javax.swing.ImageIcon("/home/david/Vídeos/searchBtnSmall.png")); // NOI18N
        btnConsCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtConsNome, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsNm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtConsCod, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsCod, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(312, 312, 312))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(btnAtualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(40, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtConsNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConsNm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtConsCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsCod))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addGap(12, 12, 12)
                        .addComponent(btnAtualizar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(btnVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdActionPerformed
        // TODO add your handling code here:
        //Metodo para abrir view de adicionar Produto
        CadastroProdutoView cpv = new CadastroProdutoView();
        cpv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddProdActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        //Botao de retorno
        TelaPrincipal tp = new TelaPrincipal();

        //Torna o jframe atual invisivel
        this.setVisible(false);

        //Torna visivel a tela anterior
        tp.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnConsNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsNmActionPerformed
        // TODO add your handling code here:

        boolean contemNumeros = false;
        boolean erro = false;

        //String para consulta do cliente
        String consultaNome = txtConsNome.getText();

        if (!txtConsNome.getText().isEmpty()) {
            for (int i = 0; i < txtConsNome.getText().length(); i++) {
                if (Character.isDigit(txtConsNome.getText().charAt(i))) {
                    contemNumeros = true;
                    erro = true;
                    break;
                }
            }

            if (contemNumeros) {
                JOptionPane.showMessageDialog(this, "O campo não pode conter números!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "O nome não pode estar em branco!", "Erro", JOptionPane.ERROR_MESSAGE);
            erro = true;
        }

        //Caso a pesquisa esteja dentro das validações
        if (erro == false) {
            List<Produto> produtoList = new ArrayList<>();
            DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Nome", "QTD Estoque", "Categoria", "Valor", "Descrição"}, 0);

            produtoList = ProdutoDAO.consultaProdutoNome(consultaNome);

            produtoList.forEach(p -> {
                Object[] row = new Object[]{p.getIdProduto(), p.getNome(), p.getQtdEstoque(), p.getCategoria(), p.getValor(), p.getDescricao()};
                model.addRow(row);
            });

            tListaProdutos.setModel(model);
        }

    }//GEN-LAST:event_btnConsNmActionPerformed

    private void btnConsCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsCodActionPerformed
        // TODO add your handling code here:
        boolean erro = false;

        try {
            Integer codProd = Integer.parseInt(txtConsCod.getText());
        } catch (NumberFormatException ex) {
            erro = true;
            JOptionPane.showMessageDialog(this, "O codigo do produto deve ser um inteiro!", "Title", JOptionPane.ERROR_MESSAGE);
        }

        if (erro == false) {

            //ESTRUTURA COM O BANCO
            try (Connection con = Conexao.getConexao(); PreparedStatement stm = con.prepareStatement("SELECT id_produto, nome, quantidade_estoque, categoria, valor, descricao FROM Produto WHERE id_produto = ?")) {
                stm.setString(1, txtConsCod.getText());

                // Executar a consulta SQL e obter os resultados
                ResultSet rs = stm.executeQuery();

                // Criar um objeto DefaultTableModel para armazenar os dados do JTable
                DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Nome", "QTD Estoque", "Categoria", "Valor", "Descrição"}, 0);

                // Preencher o modelo com os dados da consulta
                while (rs.next()) {
                    int id = rs.getInt("id_produto");
                    String nome = rs.getString("nome");
                    int quantidadeEstoque = rs.getInt("quantidade_estoque");
                    String categoria = rs.getString("categoria");
                    String valor = rs.getString("valor");
                    String descricao = rs.getString("descricao");

                    Object[] row = new Object[]{id, nome, quantidadeEstoque, categoria, valor, descricao};
                    model.addRow(row);
                }

                // Fechar os objetos ResultSet, PreparedStatement e Connection
                rs.close();
                stm.close();
                con.close();

                // Preencher o JTable com o modelo criado
                tListaProdutos.setModel(model);

            } catch (SQLException ex) {
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados!");
            }
        }

    }//GEN-LAST:event_btnConsCodActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int row = tListaProdutos.getSelectedRow();

        if (row >= 0) { // Verificar se uma linha foi selecionada
            // Exibir uma caixa de diálogo para confirmar a exclusão do cliente
            //ESTRUTURA COM O BANCO

            int option = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o produto selecionado?", "Confirmação de exclusão", JOptionPane.YES_NO_OPTION);

            if (option == JOptionPane.YES_OPTION) { // Verificar se o usuário confirmou a exclusão

                int idProduto = (int) tListaProdutos.getValueAt(row, 0);

                ProdutoDAO.excluirProduto(idProduto);

                boolean erroExclusao = false;

                erroExclusao = ProdutoDAO.excluirProduto(idProduto);

                if (erroExclusao == false) {
                    DefaultTableModel model = (DefaultTableModel) tListaProdutos.getModel();
                    model.removeRow(row);
                    JOptionPane.showMessageDialog(this, "Brinquedo excluído com sucesso.");
                }

            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um produto para excluir.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        
        int rowIndex = tListaProdutos.getSelectedRow();
        
        if(rowIndex != -1){
            // Obtém os dados da linha selecionada
            Object[] rowData = new Object[tListaProdutos.getColumnCount()];
            for (int i = 0; i < tListaProdutos.getColumnCount(); i++) {
                    rowData[i] = tListaProdutos.getValueAt(rowIndex, i);
            }
            
            // Abre o formulário de edição com os dados da linha selecionada
            AtualizarProdutoView atualizarProdutoView = new AtualizarProdutoView(rowData);
            this.dispose();
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoFormView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProd;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnConsCod;
    private javax.swing.JButton btnConsNm;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tListaProdutos;
    private javax.swing.JTextField txtConsCod;
    private javax.swing.JTextField txtConsNome;
    // End of variables declaration//GEN-END:variables
}
