/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.senac.drogarara.gui;

import com.senac.drogarara.conexao.Conexao;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class SelecionarProdutoView extends javax.swing.JFrame {

    /**
     * Creates new form SelecionarProdutoView
     */
    
    private GerarVendaView gerarVendaView;
     
    public SelecionarProdutoView(GerarVendaView gerarVendaView) {
        this.gerarVendaView = gerarVendaView;
        initComponents();
    }
    
    public SelecionarProdutoView() {
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnConsNmProd = new javax.swing.JButton();
        txtNmProd = new javax.swing.JTextField();
        txtCodProd = new javax.swing.JTextField();
        btnConsCodProd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tListaProdutoSelecionado = new javax.swing.JTable();
        btnAddCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtQtdProd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Nome do Produto:");

        jLabel3.setText("Código do Produto:");

        btnConsNmProd.setIcon(new javax.swing.ImageIcon("/home/david/Vídeos/searchBtnSmall.png")); // NOI18N
        btnConsNmProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsNmProdActionPerformed(evt);
            }
        });

        btnConsCodProd.setIcon(new javax.swing.ImageIcon("/home/david/Vídeos/searchBtnSmall.png")); // NOI18N
        btnConsCodProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsCodProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNmProd, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsCodProd, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(btnConsNmProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnConsNmProd)
                    .addComponent(txtNmProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsCodProd))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("Selecione o produto:");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tListaProdutoSelecionado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tListaProdutoSelecionado);

        btnAddCliente.setIcon(new javax.swing.ImageIcon("/home/david/Imagens/resize/verificaIcon.png")); // NOI18N
        btnAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Adicionar:");

        jLabel4.setText("Insira a quantidade:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtQtdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddCliente)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQtdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnVoltar.setIcon(new javax.swing.ImageIcon("/home/david/Vídeos/btnReturnSmall.png")); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(422, 422, 422))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnConsCodProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsCodProdActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {

            int idProd = Integer.parseInt(txtCodProd.getText());

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "O campo código do produto deve ser inteiro");
        }

        //ESTRUTURA COM O BANCO
        try (Connection con = Conexao.getConexao(); PreparedStatement stm = con.prepareStatement("SELECT id_produto, nome, quantidade_estoque, categoria, valor, descricao FROM Produto WHERE id_produto = ?")) {

            //SELECT id_produto, nome, quantidade_estoque, categoria, valor, descricao FROM Produto WHERE nome LIKE ?
            stm.setInt(1, Integer.parseInt(txtCodProd.getText()));

            // Executar a consulta SQL e obter os resultados
            ResultSet rs = stm.executeQuery();

            // Criar um objeto DefaultTableModel para armazenar os dados do JTable
            DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Nome", "Quantidade", "Categoria", "Valor", "Descrição"}, 0);

            // Preencher o modelo com os dados da consulta
            while (rs.next()) {
                int id = rs.getInt("id_produto");
                String nome = rs.getString("nome");
                long quantidade = rs.getLong("quantidade_estoque");
                String categoria = rs.getString("categoria");
                double valor = rs.getDouble("valor");
                String descricao = rs.getString("descricao");

                Object[] row = new Object[]{id, nome, quantidade, categoria, valor, descricao};
                model.addRow(row);
            }

            // Fechar os objetos ResultSet, PreparedStatement e Connection
            rs.close();
            stm.close();
            con.close();

            // Preencher o JTable com o modelo criado
            tListaProdutoSelecionado.setModel(model);

        } catch (SQLException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados!");
        }
    }//GEN-LAST:event_btnConsCodProdActionPerformed

    private void btnConsNmProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsNmProdActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
//        try {
//
//            Stri idProd = Integer.parseInt(txtCodProd.getText());
//
//        } catch (NumberFormatException ex) {
//            JOptionPane.showMessageDialog(this, "O campo código do produto deve ser inteiro");
//        }
//        
        boolean erro = false;

        if (!txtNmProd.getText().isEmpty()) {
            //ESTRUTURA COM O BANCO
            try (Connection con = Conexao.getConexao(); PreparedStatement stm = con.prepareStatement("SELECT id_produto, nome, quantidade_estoque, categoria, valor, descricao FROM Produto WHERE nome LIKE ?")) {

                //SELECT id_produto, nome, quantidade_estoque, categoria, valor, descricao FROM Produto WHERE nome LIKE ?
                stm.setString(1, txtNmProd.getText());

                // Executar a consulta SQL e obter os resultados
                ResultSet rs = stm.executeQuery();

                // Criar um objeto DefaultTableModel para armazenar os dados do JTable
                DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Nome", "Quantidade", "Categoria", "Valor", "Descrição"}, 0);

                // Preencher o modelo com os dados da consulta
                while (rs.next()) {
                    int id = rs.getInt("id_produto");
                    String nome = rs.getString("nome");
                    long quantidade = rs.getLong("quantidade_estoque");
                    String categoria = rs.getString("categoria");
                    double valor = rs.getDouble("valor");
                    String descricao = rs.getString("descricao");

                    Object[] row = new Object[]{id, nome, quantidade, categoria, valor, descricao};
                    model.addRow(row);
                }

                // Fechar os objetos ResultSet, PreparedStatement e Connection
                rs.close();
                stm.close();
                con.close();

                // Preencher o JTable com o modelo criado
                tListaProdutoSelecionado.setModel(model);

            } catch (SQLException ex) {
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados!");
            }
        }


    }//GEN-LAST:event_btnConsNmProdActionPerformed

    private void btnAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClienteActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:

        int linhaSelecionada = tListaProdutoSelecionado.getSelectedRow();
        if (linhaSelecionada != -1) {
            // Obtém o ID do cliente selecionado na tabela
            Integer idProduto = (Integer) tListaProdutoSelecionado.getValueAt(linhaSelecionada, 0);
            String nmProduto = (String) tListaProdutoSelecionado.getValueAt(linhaSelecionada, 1);
            Double valor = (Double) tListaProdutoSelecionado.getValueAt(linhaSelecionada, 4);
            Integer qtdProd = Integer.parseInt(txtQtdProd.getText());
           
//            try{
//                //Adiciona a quantidade do produto escolhido 
//               // qtdProd = Integer.parseInt(txtQtdProd.getText());
//            }catch(NumberFormatException ex){
//                erro = true;
//                JOptionPane.showMessageDialog(this, "Deve ser inserido a quantidade do produto", "Title", JOptionPane.ERROR_MESSAGE);
//            }
            
    
                // Passa o nome do cliente selecionado para a tela de gerar venda
                gerarVendaView.setTxtCodProd(idProduto);
                gerarVendaView.setTxtNmProd(nmProduto);
                gerarVendaView.setTxtValorProd(valor * qtdProd);
                gerarVendaView.setTxtQtdProd(qtdProd);
               // gerarVendaView.setTxtQtdProd(qtdProd);
       
            
            // Fecha a tela de seleção de cliente
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um produto da tabela");
        }  
    }//GEN-LAST:event_btnAddClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecionarProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecionarProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecionarProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecionarProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecionarProdutoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCliente;
    private javax.swing.JButton btnConsCodProd;
    private javax.swing.JButton btnConsNmProd;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tListaProdutoSelecionado;
    private javax.swing.JTextField txtCodProd;
    private javax.swing.JTextField txtNmProd;
    private javax.swing.JTextField txtQtdProd;
    // End of variables declaration//GEN-END:variables
}
